name: Rust

on:
  push:
    branches:
      - 'master'
      - 'staging'
  pull_request:

env:
  RUST_BACKTRACE: full
  RUST_LOG: debug

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: taiki-e/install-action@cargo-nextest
      - name: Cargo Test
        timeout-minutes: 20
        run: |
          cargo nextest run --no-fail-fast
          cargo nextest run --no-fail-fast --features tokio
      - name: Cargo Test Doc
        timeout-minutes: 20
        run: |
          cargo test --doc
          cargo test --doc --features tokio

  lint:
    name: Format and Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-check-${{ hashFiles('**/Cargo.lock') }}
      - name: Cargo Check
        run: |
          cargo check --all-targets
          cargo check --all-targets --features tokio
      - name: Cargo Format
        run: |
          cargo fmt --all --check
      - name: Cargo clippy
        run: |
          cargo clippy --all-targets --all
          cargo clippy --all-targets --all --features tokio
      
